image: gradle:8.3-jdk17

stages:
  - model_unit_tests


model-unit-tests-job:
  stage: model_unit_tests
  script:
    - chmod +x ./product/gradlew
    - ./product/app/gradlew testDebugUnitTest --stacktrace


